# Author Thibaut Rouffineau <thibaut.rouffineau@canonical.com>
# Updated by Chad Young <chad.young@dell.com>

name: mqtttestclient
version: 1
summary: MQTT client on Eclipse Foundation sandbox
description: This app is a small client using Eclipse Foundation MQTT client and using the Eclipse Foundation sandbox

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots


apps:
    mqttpublish:
        command: bin/mqttpublish

parts:
    mqtt:
        plugin: python
        source: https://github.com/eclipse/paho.mqtt.python.git
    files:
        plugin: dump
        source: .
        organize:
            ./bin/mqttpublish.py: bin/mqttpublish
